spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5434/catalog_db
    username: root
    password: root
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
