spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #catalog-service routing
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/catalog
        #order-service routing
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
          filters:
            name: CircuitBreaker
            args:
              name: orderCircuitBreaker
              fallbackUri: forward:/fallback/order
        #user-service routing
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            name: CircuitBreaker
            args:
              name: userCircuitBreaker
              fallbackUri: forward:/fallback/user
        #notification-service routing
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
          filters:
            name: CircuitBreaker
            args:
              name: notificationCircuitBreaker
              fallbackUri: forward://fallback/notification


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
resilience4j:
  circuitbreaker:
    instances:
      catalogCircuitBreaker:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 2
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      orderCircuitBreaker:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 2
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      userCircuitBreaker:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 2
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      notificationCircuitBreaker:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 2
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

server:
  port: 8080