spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #catalog-service routing
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
        #order-service routing
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8080