spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5435/order_db
    username: root
    password: root
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/pizza-realm

jwk-uri: http://localhost:8088/realms/pizza-realm/protocol/openid-connect/certs
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true