version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-catalog-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalog_db
    ports:
      - 5434:5432
    networks:
      - app-network
  app:
    image: evgvira/catalog-repo:latest
    ports:
      - 8082:8082
    environment:
      DOCKER_HOST: db:5432
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge