version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-catalog-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalog_db
    ports:
      - 5434:5432
