version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-order-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_db
    ports:
      - 5435:5432